# Generated by Django 6.0 on 2025-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
